# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM iron/java:1.8
VOLUME /tmp
ADD target/user-finder-0.1.0.jar user-finder.jar
RUN sh -c 'touch /user-finder.jar'
ENV JAVA_OPTS=""

ENTRYPOINT  ["/bin/sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /user-finder.jar"]
 

