version: '3'
services:
    # Launch vanilla mongo container
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles

    # Load init data into mongo
    mongo-init:
        image: mongo:latest
        command: >
            mongoimport --host mongodb --db affinitas --collection users --file /matches.json --jsonArray
        links:
            - mongodb
        volumes:
            - ./matches.json:/matches.json

    # Create index in mongo
    mongo-index:
        image: mongo:latest
        command: >
            mongo --host mongodb affinitas  --eval "db.users.createIndex( { 'city.loc': '2dsphere' } )"
        links:
            - mongodb
        depends_on:
            - mongo-init

    # backend service
    backend-svc:
        build:
            context: ./
            dockerfile: Dockerfile.backend
        links:
            - mongodb
        ports:
            - 8080:8080